### ISSUE TITLE
Alpha test log

### ISSUE THREAD

**Issue by s1n7e7** [Sotis-Oph/vscode-dev-plan#1]
# Базовое тестирование

## Ошибки

1. Ошибка при создании нового плана в каталоге с русскими символами

## Улучшения

1. Формат ввода времени. Предусмотреть "2:30" или 2.5 как равные. + настройка отображения
2. Горячие клавиши
3. Переход к добавленному элементу
4. Убрать пустые поля описания и показывать их только при заполнении
5. Многоуровневая вложенность и подсчет времени
6. Отметка об исполнении только для элемента дерева без потомков
7. При вводе заголовка #NNNN в начале текста рассматривать как номер тикета
8. Копирование элементов и перенос между уровнями

**Comment by Sotis-Oph** [comment]
Внесены исправления в логику и UI.
**Пока не реализовано**
- Ошибка т.к. не смог повторить. Необходимо больше данных по ошибке.
- Горячие клавиши
- Копирование и вставка

**Comment by s1n7e7** [comment]
Детали ошибки:
```log
Невозможно открыть "#740_АУВ-3000,_Автоматический_упор_для_СРН_-_связь_с_1С.devplan": Unable to resolve resource C:%5Crepo%5C%D0%A1%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0%20%D0%B8%20%D0%BF%D0%BB%D0%B0%D0%BD%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%5C/%23740_%D0%90%D0%A3%D0%92-3000%2C_%D0%90%D0%B2%D1%82%D0%BE%D0%BC%D0%B0%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D1%83%D0%BF%D0%BE%D1%80_%D0%B4%D0%BB%D1%8F_%D0%A1%D0%A0%D0%9D_-_%D1%81%D0%B2%D1%8F%D0%B7%D1%8C_%D1%81_1%D0%A1.devplan.

[2021-09-17 15:50:21.624] [renderer1] [error] Unable to resolve resource C:%5Crepo%5C%D0%A1%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0%20%D0%B8%20%D0%BF%D0%BB%D0%B0%D0%BD%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%5C/%23740_%D0%90%D0%A3%D0%92-3000%2C_%D0%90%D0%B2%D1%82%D0%BE%D0%BC%D0%B0%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D1%83%D0%BF%D0%BE%D1%80_%D0%B4%D0%BB%D1%8F_%D0%A1%D0%A0%D0%9D_-_%D1%81%D0%B2%D1%8F%D0%B7%D1%8C_%D1%81_1%D0%A1.devplan: Error: Unable to resolve resource C:%5Crepo%5C%D0%A1%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0%20%D0%B8%20%D0%BF%D0%BB%D0%B0%D0%BD%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%5C/%23740_%D0%90%D0%A3%D0%92-3000%2C_%D0%90%D0%B2%D1%82%D0%BE%D0%BC%D0%B0%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D1%83%D0%BF%D0%BE%D1%80_%D0%B4%D0%BB%D1%8F_%D0%A1%D0%A0%D0%9D_-_%D1%81%D0%B2%D1%8F%D0%B7%D1%8C_%D1%81_1%D0%A1.devplan
    at s.doCreateReferencedObject (vscode-file://vscode-app/c:/Users/astafiev.se/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2424:114106)
    at s.doCreateReferencedObject (vscode-file://vscode-app/c:/Users/astafiev.se/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2424:114069)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async i.acquire (vscode-file://vscode-app/c:/Users/astafiev.se/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:17:14802)
    at async d.createModelReference (vscode-file://vscode-app/c:/Users/astafiev.se/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2424:115742)
    at async vscode-file://vscode-app/c:/Users/astafiev.se/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1700:50584
    at async Object.resolveWebview (vscode-file://vscode-app/c:/Users/astafiev.se/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2429:60966)
    at async i.tryRevive (vscode-file://vscode-app/c:/Users/astafiev.se/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1806:11681)
    at async vscode-file://vscode-app/c:/Users/astafiev.se/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1806:11789
[2021-09-17 15:50:21.624] [renderer1] [error] Error: Unable to resolve resource C:%5Crepo%5C%D0%A1%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0%20%D0%B8%20%D0%BF%D0%BB%D0%B0%D0%BD%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%5C/%23740_%D0%90%D0%A3%D0%92-3000%2C_%D0%90%D0%B2%D1%82%D0%BE%D0%BC%D0%B0%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D1%83%D0%BF%D0%BE%D1%80_%D0%B4%D0%BB%D1%8F_%D0%A1%D0%A0%D0%9D_-_%D1%81%D0%B2%D1%8F%D0%B7%D1%8C_%D1%81_1%D0%A1.devplan
    at s.doCreateReferencedObject (vscode-file://vscode-app/c:/Users/astafiev.se/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2424:114106)
    at s.doCreateReferencedObject (vscode-file://vscode-app/c:/Users/astafiev.se/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2424:114069)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async i.acquire (vscode-file://vscode-app/c:/Users/astafiev.se/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:17:14802)
    at async d.createModelReference (vscode-file://vscode-app/c:/Users/astafiev.se/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2424:115742)
    at async vscode-file://vscode-app/c:/Users/astafiev.se/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1700:50584
    at async Object.resolveWebview (vscode-file://vscode-app/c:/Users/astafiev.se/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2429:60966)
    at async i.tryRevive (vscode-file://vscode-app/c:/Users/astafiev.se/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1806:11681)
    at async vscode-file://vscode-app/c:/Users/astafiev.se/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1806:11789
```

**Comment by Sotis-Oph** [comment]
Ошибка устранена в версии 0.3.0
